application: zhengfablog
version: 2
runtime: python27
api_version: 1
threadsafe: false


handlers:

- url: /themes
  static_dir: themes/
- url: /static
  static_dir: static/

- url: /ckeditor/.*
  script: $PYTHON_LIB/google/appengine/ext/zipserve

- url: /admin
  script: admin.py
  login: admin
- url: /admin/.*
  script: admin.py
  login: admin


- url: /.*
  script: weblog.py

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest

